"use client";

/**
 * MadrashaOS — Lucide icon resolver (Task 8-a)
 *
 * Maps a kebab-case icon name string (e.g. "graduation-cap") stored in
 * the CMS content to the actual Lucide icon component, so the CMS admin
 * can edit which icon a nav item / program card uses without touching
 * code.
 *
 * Falls back to the `Sparkles` icon when the requested name is not
 * available — this is the safest generic visual on the MadrashaOS
 * palette.
 */

import * as React from "react";
import {
  Accessibility, AlertCircle, AlertTriangle, ArrowDownLeft,
  ArrowDownToLine, ArrowLeft, ArrowLeftRight, ArrowRight,
  ArrowUpCircle, ArrowUpFromLine, ArrowUpRight, Award, Ban,
  BarChart3, BedDouble, Bell, BellOff, BookOpen, BookMarked,
  Briefcase, Bug, Building2, Bus, Calculator, CalendarDays,
  CalendarOff, CalendarPlus, Check, CheckCheck, CheckCircle2,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp, CircleDot,
  ClipboardCheck, ClipboardList, Clock, CloudUpload, CreditCard,
  DatabaseBackup, Download, Droplet, ExternalLink, Eye, Facebook,
  FileArchive, FileCheck2, FileEdit, FileImage, FileSpreadsheet,
  FileText, FileType, Filter, Fuel, Gauge, Gift, Globe,
  GraduationCap, GripVertical, Hand, HandCoins, HandHeart, Hash,
  Heart, History, Home, Info, Instagram, Key, Keyboard, Landmark,
  Languages, Laptop, LayoutDashboard, LayoutGrid, Library, LifeBuoy,
  ListChecks, Loader2, Lock, LogOut, Mail, MapPin, Megaphone, Menu,
  MessageCircle, Mic, Minus, Monitor, Moon, MoreHorizontal,
  MousePointerClick, Package, PackageCheck, Palette, PanelLeftClose,
  PanelLeftOpen, PartyPopper, Pencil, Phone, Play, PlayCircle, Plus,
  Presentation, Receipt, Redo2, RefreshCw, Reply, RotateCcw, Save,
  Scale, ScanLine, Scroll, ScrollText, Search, Send, Settings,
  Settings2, Share, ShieldAlert, ShieldCheck, ShoppingBag,
  ShoppingCart, Smartphone, Sofa, Sparkles, Star, Stethoscope, Sun,
  Tablet, Trash2, TrendingDown, TrendingUp, Trophy, Truck, Twitter,
  Type, Undo2, Upload, User, UserCheck, UserCircle, UserMinus,
  UserPlus, UserRound, UserSearch, Users, UsersRound,
  UtensilsCrossed, Volume2, Wallet, WifiOff, Wrench, X, XCircle, Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-down-left": ArrowDownLeft,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "arrow-up-circle": ArrowUpCircle,
  "arrow-up-from-line": ArrowUpFromLine,
  "arrow-up-right": ArrowUpRight,
  award: Award,
  ban: Ban,
  "bar-chart-3": BarChart3,
  "bed-double": BedDouble,
  bell: Bell,
  "bell-off": BellOff,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  briefcase: Briefcase,
  bug: Bug,
  "building-2": Building2,
  bus: Bus,
  calculator: Calculator,
  "calendar-days": CalendarDays,
  "calendar-off": CalendarOff,
  "calendar-plus": CalendarPlus,
  check: Check,
  "check-check": CheckCheck,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-dot": CircleDot,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "cloud-upload": CloudUpload,
  "credit-card": CreditCard,
  "database-backup": DatabaseBackup,
  download: Download,
  droplet: Droplet,
  "external-link": ExternalLink,
  eye: Eye,
  facebook: Facebook,
  "file-archive": FileArchive,
  "file-check-2": FileCheck2,
  "file-edit": FileEdit,
  "file-image": FileImage,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "file-type": FileType,
  filter: Filter,
  fuel: Fuel,
  gauge: Gauge,
  gift: Gift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "grip-vertical": GripVertical,
  hand: Hand,
  "hand-coins": HandCoins,
  "hand-heart": HandHeart,
  hash: Hash,
  heart: Heart,
  history: History,
  home: Home,
  info: Info,
  instagram: Instagram,
  key: Key,
  keyboard: Keyboard,
  landmark: Landmark,
  languages: Languages,
  laptop: Laptop,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  library: Library,
  "life-buoy": LifeBuoy,
  "list-checks": ListChecks,
  "loader-2": Loader2,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  menu: Menu,
  "message-circle": MessageCircle,
  mic: Mic,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  "mouse-pointer-click": MousePointerClick,
  package: Package,
  "package-check": PackageCheck,
  palette: Palette,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  "party-popper": PartyPopper,
  pencil: Pencil,
  phone: Phone,
  play: Play,
  "play-circle": PlayCircle,
  plus: Plus,
  presentation: Presentation,
  receipt: Receipt,
  "redo-2": Redo2,
  "refresh-cw": RefreshCw,
  reply: Reply,
  "rotate-ccw": RotateCcw,
  save: Save,
  scale: Scale,
  "scan-line": ScanLine,
  scroll: Scroll,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  settings: Settings,
  "settings-2": Settings2,
  share: Share,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sofa: Sofa,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  tablet: Tablet,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  trophy: Trophy,
  truck: Truck,
  twitter: Twitter,
  type: Type,
  "undo-2": Undo2,
  upload: Upload,
  user: User,
  "user-check": UserCheck,
  "user-circle": UserCircle,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "user-search": UserSearch,
  users: Users,
  "users-round": UsersRound,
  "utensils-crossed": UtensilsCrossed,
  "volume-2": Volume2,
  wallet: Wallet,
  "wifi-off": WifiOff,
  wrench: Wrench,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
};

/**
 * Resolve a kebab-case icon name to a Lucide icon component.
 * Falls back to Sparkles when the icon name is not in the ICON_MAP.
 */
export function resolveIcon(name?: string): LucideIcon {
  if (!name) return Sparkles;
  return ICON_MAP[name] ?? Sparkles;
}

/**
 * Convenience wrapper that renders the resolved icon with className.
 * Use as <DynamicIcon name="graduation-cap" className="h-4 w-4" />.
 */
export function DynamicIcon({
  name,
  className,
}: {
  name?: string;
  className?: string;
}): React.ReactElement {
  const Icon = resolveIcon(name);
  return React.createElement(Icon, { className });
}
